# Generated by Django 4.2.3 on 2023-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='units_in_stock',
            field=models.BigIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='units_sold',
            field=models.BigIntegerField(),
        ),
    ]
