# Generated by Django 4.2.3 on 2023-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.charfield><django.db.models.fields.BigAutoField>', unique=True),
        ),
    ]
