# Generated by Django 4.2.3 on 2023-08-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
