# Generated by Django 4.2.3 on 2023-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shoppingcart_ordered_shoppingcart_ordered_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_items', models.IntegerField()),
                ('items', models.ManyToManyField(to='core.item')),
            ],
        ),
    ]
