# Generated by Django 4.2.3 on 2023-08-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='category_image',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
