# Generated by Django 4.2.3 on 2023-08-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_itemcategory_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='category_image',
            new_name='image',
        ),
    ]
