# Generated by Django 4.2.3 on 2023-08-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_category_image_itemcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='image',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
