# Generated by Django 4.2.3 on 2023-08-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_item_image_alter_itemcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='img/'),
        ),
    ]
