# Generated by Django 4.2.3 on 2023-08-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ordereditem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='main_image',
        ),
    ]
