# Generated by Django 4.2.3 on 2023-08-26 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_alter_item_main_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='number_of_items',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
