# Generated by Django 4.2.3 on 2023-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_item_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='name_lowercase',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
