# Generated by Django 4.2.3 on 2023-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_itemcategory_name_lowercase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name_lowercase',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(to='core.itemattribute'),
        ),
    ]
