# Generated by Django 4.2.3 on 2023-09-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_itemattribute_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='core.itemattribute'),
        ),
        migrations.AlterField(
            model_name='itemattribute',
            name='value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name_lowercase',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
