# Generated by Django 4.2.3 on 2023-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_item_attributes_alter_itemattribute_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name_plural': 'Item categories'},
        ),
        migrations.RemoveField(
            model_name='itemattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='values',
            field=models.ManyToManyField(to='core.itemattributevalue'),
        ),
    ]
