# Generated by Django 4.2.3 on 2023-10-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_itemattributevalue_alter_itemcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, default='', upload_to='img/items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='units_in_stock',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='units_sold',
            field=models.BigIntegerField(default=0),
        ),
    ]
